version: '3.8'

services:
  taxi_api:
    container_name: taxi_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database
    env_file: ./.env
    restart: unless-stopped

  database:
    image: postgis/postgis:13-3.1
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local