import { DataSource } from 'typeorm';
import * as bcrypt from 'bcrypt';

import { Driver } from '../../entities/Driver/driver.entity';
import { DocumentType } from '../../types/enums/document-type.enum';

export async function seedDrivers(dataSource: DataSource) {
  const repo = dataSource.getRepository(Driver);
  const drivers = repo.create([
    {
      name: 'Nearby Driver 1',
      lastName: 'Ramírez',
      email: 'nearby1@example.com',
      password: await bcrypt.hash('pass123', 10),
      isActive: true,
      license: 'LIC123',
      document: 'DOC1233890',
      phoneNumber: '3210000001',
      documentType: DocumentType.CC,
      location: {
        type: 'Point',
        coordinates: [-74.245, 4.65],
      },
    },
    {
      name: 'Nearby Driver 2',
      lastName: 'López',
      email: 'nearby2@example.com',
      password: await bcrypt.hash('pass123', 10),
      isActive: true,
      license: 'LIC456',
      document: 'DOC4569876',
      phoneNumber: '3210000002',
      documentType: DocumentType.CC,
      location: {
        type: 'Point',
        coordinates: [-74.248, 4.647],
      },
    },
    {
      name: 'Nearby Driver 3',
      lastName: 'Martínez',
      email: 'nearby3@example.com',
      password: await bcrypt.hash('pass123', 10),
      isActive: true,
      license: 'LIC789',
      document: 'DOC7893765',
      phoneNumber: '3210000003',
      documentType: DocumentType.CC,
      location: {
        type: 'Point',
        coordinates: [-74.244, 4.651],
      },
    },
    {
      name: 'Nearby Driver 4',
      lastName: 'García',
      email: 'nearby4@example.com',
      password: await bcrypt.hash('pass123', 10),
      isActive: true,
      license: 'LIC012',
      document: 'DOC012987',
      phoneNumber: '3210000004',
      documentType: DocumentType.CC,
      location: {
        type: 'Point',
        coordinates: [-74.246, 4.649],
      },
    },
    {
      name: 'Nearby Driver 5',
      lastName: 'Hernández',
      email: 'nearby5@example.com',
      password: await bcrypt.hash('pass123', 10),
      isActive: true,
      license: 'LIC345',
      document: 'DOC3453456',
      phoneNumber: '3210000005',
      documentType: DocumentType.CC,
      location: {
        type: 'Point',
        coordinates: [-74.242, 4.653],
      },
    },
    {
      name: 'Nearby Driver 6',
      lastName: 'Pérez',
      email: 'nearby6@example.com',
      password: await bcrypt.hash('pass123', 10),
      isActive: true,
      license: 'LIC678',
      document: 'DOC6786543',
      phoneNumber: '3210000006',
      documentType: DocumentType.CC,
      location: {
        type: 'Point',
        coordinates: [-74.243, 4.652],
      },
    },
    // {
    //   name: 'Nearby Driver 7',
    //   lastName: 'Fernández',
    //   email: 'nearby7@example.com',
    //   password: await bcrypt.hash('pass123', 10),
    //   isActive: true,
    //   license: 'LIC901',
    //   document: 'DOC901',
    //   phoneNumber: '3210000007',
    //   documentType: DocumentType.CC,
    //   location: {
    //     type: 'Point',
    //     coordinates: [-74.249, 4.646],
    //   },
    // },
    // {
    //   name: 'Nearby Driver 8',
    //   lastName: 'Gómez',
    //   email: 'nearby8@example.com',
    //   password: await bcrypt.hash('pass123', 10),
    //   isActive: true,
    //   license: 'LIC234',
    //   document: 'DOC234',
    //   phoneNumber: '3210000008',
    //   documentType: DocumentType.CC,
    //   location: {
    //     type: 'Point',
    //     coordinates: [-74.24, 4.644],
    //   },
    // },
    // {
    //   name: 'Nearby Driver 9',
    //   lastName: 'Sánchez',
    //   email: 'nearby9@example.com',
    //   password: await bcrypt.hash('pass123', 10),
    //   isActive: true,
    //   license: 'LIC567',
    //   document: 'DOC567',
    //   phoneNumber: '3210000009',
    //   documentType: DocumentType.CC,
    //   location: {
    //     type: 'Point',
    //     coordinates: [-74.241, 4.655],
    //   },
    // },
    // {
    //   name: 'Nearby Driver 10',
    //   lastName: 'Díaz',
    //   email: 'nearby10@example.com',
    //   password: await bcrypt.hash('pass123', 10),
    //   isActive: true,
    //   latitude: 4.657,
    //   longitude: -74.243,
    //   license: 'LIC890',
    //   document: 'DOC890',
    //   phoneNumber: '3210000010',
    //   documentType: DocumentType.CC,
    //   location: {
    //     type: 'Point',
    //     coordinates: [-74.243, 4.657],
    //   },
    // },
    {
      name: 'Far Driver 1',
      lastName: 'Castro',
      email: 'far1@example.com',
      password: 'pass789567',
      isActive: true,
      license: 'LIC789',
      document: 'DOC789456',
      phoneNumber: '3210000003',
      documentType: DocumentType.CC,
      location: {
        type: 'Point',
        coordinates: [-74.25, 4.62],
      },
    },
    {
      name: 'Far Driver 2',
      lastName: 'Gómez',
      email: 'far2@example.com',
      password: 'pass000',
      isActive: true,
      license: 'LIC000',
      document: 'DOC0002345',
      phoneNumber: '3210000004',
      location: {
        type: 'Point',
        coordinates: [-74.24, 4.68],
      },
    },
  ]);

  await repo.save(drivers);
  console.log('Drivers seeded');
}
